Work_Manager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', 'tasks_manager.views.index', name='public_index'),
                       url(r'^create/', include('tasks_manager.urls', namespace='create')),
                       url(r'^delete', include('tasks_manager.urls', namespace='delete')),
                       url(r'^edit', include('tasks_manager.urls', namespace='edit')),
                       url(r'^search', include('tasks_manager.urls', namespace='search')),
                       url(r'^list-', include('tasks_manager.urls', namespace='list', app_name='tasks_manager')),
                       url(r'^detail', include('tasks_manager.urls', namespace='detail')),
                       url(r'^accounts', include('tasks_manager.urls', namespace='accounts')),
                       url(r'^forum', include('forum.urls', namespace='forums')),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.conf.urls import url, patterns
from .views import login, index, newthread

urlpatterns = patterns('',
                       url(r'login/$', login, name='login'),
                       url(r'', index, name='index'),
                       url(r'/newthread/$', newthread, name='newthread'),
                       )

tasks_manager/urls.py
from django.conf.urls import patterns, url

from .views import UpdateProjectList, task_detail, task_list, task_ajax, project_detail, project_list
from .views import create_task, create_project, create_developer, create_supervisor
from .views import user_login, user_profile, user_logout, task_delete
urlpatterns = patterns('',
                       url(r'_task$', create_task, name='create_task'),
                       url(r'_project$', create_project, name='create_project'),
                       url(r'_developer$', create_developer, name='create_developer'),
                       url(r'_supervisor$', create_supervisor, name='create_supervisor'),
                       url(r'_task$', task_delete, name='task_delete'),
                       url(r'_project/$', UpdateProjectList.as_view(), name='edit_project'),
                       url(r'ajax/$', task_ajax, name='task_search_ajax'),
                       url(r'task_(?P<pk>\d+)$', task_detail, name='task_detail'),
                       url(r'_project_(?P<pk>\d+)$', project_detail, name='project_detail'),
                       url(r'task$', task_list, name='list_task'),
                       url(r'_project$',project_list, name='project_list'),
                       url(r'_login$', user_login, name='user_login'),
                       url(r'_logout$', user_logout, name='user_logout'),
                       url(r'_user_profile', user_profile, name='user_profile'),
                       )

tasks_manager/models.py
# coding: utf-8

from django.db import models

# Create your models here.


class UserProfile(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'用户名字')
    login = models.CharField(max_length=25, verbose_name=u'登录')
    password = models.CharField(max_length=100, verbose_name=u'密码')
    password_bis = models.CharField(max_length=100, verbose_name=u'确认输入的密码')
    phone = models.CharField(max_length=20, verbose_name=u'电话号码')
    born_date = models.DateField(
        verbose_name=u'出生日期', null=True, blank=True, default=None)
    last_connection = models.DateTimeField(
        verbose_name=u'最后连接日期', null=True, blank=True, default=None)
    email = models.EmailField(verbose_name=u'电子邮箱地址')
    years_seniority = models.IntegerField(verbose_name=u'资历如何', default=0)
    date_created = models.DateField(null=True,blank=True,verbose_name=u'何时过生日？', auto_now_add=True)

    def __unicode__(self):
        return self.name


class Supervisor(UserProfile):
    specialisation = models.CharField(
        max_length=50, verbose_name=u'特别指派的管理账户',)


class Developer(UserProfile):
    supervisor = models.ForeignKey(Supervisor, verbose_name=u'此开发者的管理者是？')


class Project(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'项目名称')
    description = models.CharField(max_length=1000, verbose_name=u'项目描述')
    client_name = models.CharField(max_length=1000, verbose_name=u'客户的名字是？')

    def __unicode__(self):
        return self.title


class Task(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'任务名称')
    description = models.CharField(max_length=1000, verbose_name=u'任务描述')
    time_elapsed = models.IntegerField(
        verbose_name=u'任务所消耗时间', null=True, default=None, blank=True)
    importance = models.IntegerField(verbose_name=u'任务重要性',)
    project = models.ForeignKey(
        Project, verbose_name=u'所属哪个项目', null=True, default=None, blank=True)
    developer = models.ForeignKey(Developer, verbose_name=u'任务所属开发者')

    def __unicode__(self):
        return self.title

    def natural_key(self):
        return (self.title, self.description,
                self.time_elapsed, self.importance, self.project, self.developer)

tasks_manager/forms.py
# -*- coding: utf-8 -*-
from django import forms


class ProjectForm(forms.Form):
    title = forms.CharField(label=u'项目名称')
    description = forms.CharField(widget=forms.Textarea, )
    client_name = forms.CharField()

    def send_mail(self):
        pass

tasks_manager/views.py
# -*- coding:utf-8 -*-

import re
import json
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
# from django.views.decorators.csrf import csrf_exempt
from .models import Project, Task, Supervisor, Developer, UserProfile
# from django.contrib.auth.decorators import login_required, permission_required
# from django.contrib.auth import authenticate, login, logout
# from django.utils.decorators import method_decorator
from django.views.generic import ListView, View
# from Work_Manager.utils import anti_resubmit
# Create your views here.

try:
    from functools import wraps
except ImportError:
    from django.utils.functional import wraps  # Python 2.4 fallback.
import random
from django.conf import settings
from django.utils.decorators import available_attrs
from hashlib import md5 as md5_constructor

if hasattr(random, 'SystemRandom'):
    randrange = random.SystemRandom().randrange
else:
    randrange = random.randrange
_MAX_CSRF_KEY = 18446744073709551616L     # 2 << 63


def _get_new_submit_key():
    return md5_constructor("%s%s" % (randrange(0, _MAX_CSRF_KEY), settings.SECRET_KEY)).hexdigest()


def anti_resubmit(page_key=''):
    def decorator(view_func):
        @wraps(view_func, assigned=available_attrs(view_func))
        def _wrapped_view(request, *args, **kwargs):
            if request.method == 'GET':
                request.session['%s_submit' % page_key] = _get_new_submit_key()
                print 'session:' + request.session.get('%s_submit' % page_key)
            elif request.method == 'POST':
                old_key = request.session.get('%s_submit' % page_key, '')
                if old_key == '':
                    return HttpResponseRedirect(reverse_lazy('public_index'))
                request.session['%s_submit' % page_key] = ''
            return view_func(request, *args, **kwargs)
        return _wrapped_view
    return decorator


def login_required():
    pass


# @anti_resubmit(page_key='user_login')
def user_login(request):
    login_status = []
    if request.method == 'POST':
        try:
            m = UserProfile.objects.get(login=request.POST['login_name'])
            if m.password == request.POST['login_password']:
                request.session['user_id'] = m.id
                login_status.append('allow_login')
                return HttpResponseRedirect(reverse_lazy('accounts:user_profile'))
        except UserProfile.DoesNotExist:
            return HttpResponse("your username and password didn't match.")
    else:
        return render(request, 'accounts/login.html', )


def user_logout(request):
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse_lazy('public_index'))


def user_profile(request):
    return render(request, 'user_profile.html')


def task_list(request):
    tasks = Task.objects.filter()
    return render(request, 'task_list.html', {'tasks':tasks})


def task_detail(request, pk):
    single_task = Task.objects.get(pk=pk)
    return render(request, 'task_detail.html', {'task': single_task})


def task_ajax(request):
    if request.method == 'GET' and request.is_ajax():
        try:
            form_task = request.GET.get('query', '')
        except ValueError:
            return HttpResponse('form task is not exist')
        task = Task.objects.filter(title__icontains=form_task)
        if not task:
            return JsonResponse({'errors': '没有查到任何内容，请检查您输入的内容是否为task的名称'}, safe=False)
        pre_json_list = []
        for i in task:
            pre_json_list.append({
                'id': i.id,
                'title': i.title,
                'description': i.description,
                'developer': i.developer.supervisor.name
            })
        return JsonResponse(pre_json_list, safe=False)
    if request.method == 'POST' and request.is_ajax():
        return HttpResponse('client ajax request is not working')


def task_delete(request):
    pass


def index(request):
    queryset = Project.objects.all()
    task = Task.objects.filter()
    context_dict = \
        {
            'queryset': queryset, 'action': "目前开发的项目", 'search': u'全局搜索',
            'task': task,
        }
    return render(request, 'index.html', context_dict)


def project_detail(request, pk):
    project = Project.objects.get(id=pk)
    return render(request, 'project_detail.html', {'project': project})


class UpdateProjectList(ListView):
    model = Project
    context_object_name = 'projects'


def create_project(request):
    input_name = ['title', 'description', 'client_name']
    projects = Project.objects.all()
    context_dict = {'projects': projects}
    errors = []
    if request.POST:
        for x in input_name:
            if x in request.POST:
                title = request.POST.get('title', '')
                if title == '':
                    errors.append('title is not allow leaving a blank')
                description = request.POST.get('description', '')
                client_name = request.POST.get('client_name', '')
                new_project = Project(
                    title=title, description=description, client_name=client_name)
                new_project.save()
                return render(request, 'create_project', {'errors': errors})
    else:
        return render(request, 'create_project.html', context_dict)


def project_list(request):
    return render(request, 'project_list.html')


def create_developer(request, ):
    input_name = ['name', 'login', 'password', 'supervisor']
    u = UserProfile.objects.filter()
    if request.POST:
        for x in input_name:
            if x in request.POST:
                name = request.POST.get('name', '')
                if name == '':
                    er = {"errors": "your name can't leave a blank here!"}
                    return er
                for user in u.values():
                    if name in user['name']:
                        return HttpResponse("the name is already exist")
                login = request.POST.get('login', '')
                if not login:
                    return HttpResponse("your login name is blank, conform it! ")
                password = request.POST.get('password', '')
                if password == '':
                    return HttpResponse("your password is a blank, correct it!")
                supervisor_id = request.POST.get('supervisor', '')
                supervisor = Supervisor.objects.get(id=supervisor_id)
                new_dev = Developer(
                    name=name, login=login, password=password, supervisor=supervisor)
                new_dev.save()
                return HttpResponse("Developer added")
    else:
        supervisors_list = Supervisor.objects.all()
        context_dict = {'supervisors_list': supervisors_list}
        return render(request, 'create_developer.html', context_dict)


def connection(request):
    return render(request, 'connection.html')


def create_task(request):
    t = Task.objects.all()
    context_dict = {'tasks': t}
    return render(request, 'create_task.html', context_dict)


def create_supervisor(request):
    # supervisors = Supervisor.objects.all()
    # context_dict = {'supervisors': supervisors}
    input_name = ['spv_name', 'spv_login', 'spv_password', 'spv_password_2', 'spv_born_date', 'spv_phone',
                  'spv_email', 'spv_years_seniority', 'spv_specialisation']
    errors = []

    if request.POST:
        for i in input_name:
            if i in request.POST:
                name = request.POST.get('spv_name', '')
                u_name = UserProfile.objects.filter(name=name)
                if not re.search(r'^\w+$', name):
                    errors.append(u'密码不匹配规则')
                login = request.POST.get('spv_login', '')
                password = request.POST.get('spv_password', '')
                password_bis = request.POST.get('spv_password_2', '')
                phone = request.POST.get('spv_phone', '')
                email = request.POST.get('spv_email', '')
                born_date = request.POST.get('spv_born_date', '')
                years_seniority = request.POST.get('spv_years_seniority', '')
                specialisation = request.POST.get('spv_specialisation', '')
                if not password == password_bis:
                    return HttpResponse(u'两次密码不相等')
                if email == u_name[0].__dict__['email']:
                    errors.append(u'该邮箱已经被注册')
                new_supervisor = Supervisor(name=name, login=login, password=password, password_bis=password_bis,
                                            phone=phone,
                                            email=email, born_date=born_date, years_seniority=years_seniority,
                                            specialisation=specialisation
                                            )
                new_supervisor.save()
                return render(request, 'create_supervisor.html', {'errors': errors})
    else:
        return render(request, 'create_supervisor.html', )

templates/tasksmanager/create_developer.html
{% extends 'base.html' %}
{% block title %}
Create Developer
{% endblock %}

{% block h1 %}
<div style="margin-left:500px; margin-right: 500px;">
    <p>Create Developer</p>
</div>
{% endblock %}

{% block article_content %}
    <style>
        .biankuang{
            border: 1px solid #e38d13;
            background-color: #9d9d9d;
            padding: 20px;
            width: 290px;
            position: relative;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
        }
    </style>
    <div>
        <script>
        $(document).ready(function(){

            $("input#name").blur(function(){
                var n = $("#name").val();
                $.post("{% url 'tasks_manager:create_developer' %}", {'name': n}, function(){
                    alert('works')
            });
        });
        </script>
    </div>
    <div class="biankuang">
          <form method="post" action="{% url 'tasks_manager:create_developer' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td><label>用户名</label></td>
                    <span id="result"></span>
                    <td>
                        <input type="text" name="name"  id="name" style="width: 50px;" maxlength="30"/>
                    </td>
                </tr>
                <tr>
                    <td><label>登录名</label></td>
                    <td>
                        <input type="text" name="login" maxlength="30"/>
                    </td>
                </tr>
                <tr>
                    <td><label>密码</label></td>
                    <td>
                        <input type="text" name="password" />
                    </td>
                </tr>
                <tr>
                    <td><label>再次输入密码</label></td>
                    <td>
                        <input type="text" name="password_bis" />
                    </td>
                </tr>
                <tr>
                    <td>Supervisor</td>
                    <td>
                        <select name="supervisor">
                            {% for supervisor in supervisors_list %}
                            <option value="{{ supervisor.id }}">
                                {{ supervisor.name }}
                            </option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="验证它" />
                    </td>
                </tr>
            </table>
          </form>
    </div>

{% endblock %}

templates/tasksmanager/create_project.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
{% endblock %}

{% block h1 %}
{% endblock %}

{% block article_content %}
    <div class="container">
        <form method="post" action="{% url 'tasks_manager:create_project' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">project title</label>
                <input type="text" name="title" class="form-control" placeholder="项目名字"/>
            </div>
            <div class="form-group">
                <label for="description">项目描述</label>
                <textarea name="description" class="form-control" placeholder="对项目进行描述"></textarea>
            </div>
            <div>
                <label for="client_name">客户姓名</label>
                <input type="text" name="client_name" class="form-control" placeholder="客户的公司名字"/>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">提交输入内容</button>
        </form>
    </div>
<hr>
    <br>
    <div class="container">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label for="firstname" class="col-sm-2 control-label">名字</label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="firstname"
                           placeholder="请输入名字">
                </div>
            </div>
            <div class="form-group">
                <label for="lastname" class="col-sm-2 control-label">姓</label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="lastname"
                           placeholder="请输入姓">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> 请记住我
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">登录</button>
                </div>
            </div>
        </form>
    </div>


{% endblock %}

templates/tasksmanager/create_supervisor.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
{% endblock %}

{% block h1 %}
{% endblock %}

{% block article_content %}

    <div class="container">
        <form method="post" action="{% url 'tasks_manager:create_supervisor' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="spv_name">管理者名字</label>
                {% if errors %}
                <ul>
                    {% for obj in errors %}
                    <li style="color: red;">{{ obj }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <input type="text" class="form-control" name="spv_name" placeholder="管理者的名字"/>
            </div>
            <div class="form-group">
                <label for="spv_login">登录名</label>
                <input type="text" class="form-control" name="spv_login" placeholder="管理者的登录名"/>
            </div>
            <div class="form-group">
                <label for="spv_password">登录密码</label>
                <input type="password" class="form-control" name="spv_password" placeholder="密码">
            </div>
            <div class="form-group">
                <label for="spv_password_2">确认登录密码</label>
                <input type="password" class="form-control" name="spv_password_2" placeholder="再次确认输入的密码">
            </div>
            <div class="form-group">
                <label for="spv_phone">电话号码</label>
                <input type="tel" class="form-control" name="spv_phone" placeholder="电话号码">
            </div>
            <div class="form-group">
                <label for="spv_born_date">个人出生日期</label>
                <input type="date" class="form-control" name="spv_born_date" placeholder="出生日期">
            </div>
            <div class="form-group">
                <label for="spv_email">电子邮件</label>
                <input type="email" class="form-control" name="spv_email" placeholder="电邮地址">
            </div>
            <div class="form-group">
                <label for="spv_years_seniority">个人资历年限</label>
                <input type="number" class="form-control" name="spv_years_seniority" placeholder="工作几年">
            </div>
            <div class="form-group">
                <label for="spv_special">特别指派的人员</label>
                <input type="text" class="form-control" name="spv_special" placeholder="特派员">
            </div>
            <div class="form-group">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-success">提交内容</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

templates/tasksmanager/create_task.html
{% extends 'base.html' %}

{% block title %}
    create for the task
{% endblock %}

{% block article_content %}
    <div class="container" xmlns="http://www.w3.org/1999/html">
        <form method="post" action="{% url 'tasks_manager:create_task' %}">
            {% csrf_token %}
            <div class="form-group-sm">
                <label>任务描述</label>
                <input type="text" class="form-control" name="title" placeholder="任务名称"/>
            </div>
            <br>

            <div class="form-group-sm">
                <label>任务描述</label>
                <textarea class="form-control" name="description" placeholder="任务概述" style="width: auto"></textarea>
            </div>
            <br>
            <div class="form-group">
                <label for="name">选择列表</label>
                <input type="text" name="developer" class="form-control"/>
            </div>


            <div class="form-group">
                <button type="submit" class="btn btn-group">提交内容</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/tasksmanager/project_detail.html
{% extends 'base.html' %}

{% block article_content %}
<h3>项目名称： {{ project.title }}</h3>
<h4>所属客户 ： {{ project.client_name }}</h4>

<p>
    对此项目的描述：<br><br>
   <span> {{ project.description }} </span>
</p>
{% endblock %}

templates/tasksmanager/project_list.html
{% extends 'base.html' %}

{% block title %}
the list of all projects
{% endblock %}

{% block article_content %}
            <div>
                <table class="table table-hover">
                    <caption>悬停表格布局</caption>
                    <thead>
                    <tr>
                        <th>项目名称</th>
                        <th>项目描述</th>
                        <th>项目所属客户</th>
                        <th>请选择</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for p in projects %}
                        <tr>
                            <td><a href="{% url 'project_detail' pk=1 %}">{{ p.title }}</a></td>
                            <td>{{ p.description }}</td>
                            <td>{{ p.client_name }}</td>
                            <td>
                                <lable><input type="checkbox" class="checkbox" name="pj_name"></lable>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
                <div class="form-group">
                    <div class="col-sm-offset-9 col-sm-10">
                        <button type="submit" class="btn btn-primary">编辑所选</button>
                        <input type="button" id="checkAll" value="全选"/>
                    </div>
                </div>
            </div>

        <div class="paginator">
            <span class="">
                {% if projects.has_previous %}
                    <a href="?page={{ projects.previous_page_number }}">Pre</a>
                {% else %}
                    <span class=""></span>
                {% endif %}
                <span class="pagination">
                    Page {{ projects.number }} of {{ projects.pagiator.num_pages }}
                </span>
                {% if projects.has_next %}
                    <a href="?page={{ projects.next_page_number }}">next</a>
                {% else %}
                    <span class=""></span>
                {% endif %}
            </span>
        </div>
        <script>
        $('#checkAll').click(checkAll); // 全选
        $('#checkFootball').click(checkFootball); // 单选足球
        function checkAll() {
            $('input [type="checkbox"][name="pj_name"]').attr("checked", true);
            $('[name="pj_name"]:checkbox').attr("checked", true);
        }

        function checkFootball(){
            $("[name='item']:checkbox").each(function(){
               if(this.value == 'football')
               {this.checked = true;}
            });
        }
        </script>
{% endblock %}

templates/tasksmanager/task_detail.html
{% extends 'base.html' %}

{% block title %}
task detail
{% endblock %}

{% block article_content %}
    <div class="container">
    <table class="table">
   <caption>上下文表格布局</caption>
   <thead>
      <tr>
         <th>任务名称</th>
         <th>任务的概述</th>
         <th>所属管理者</th>
      </tr>
   </thead>
   <tbody>
      <tr class="active">
         <td>{{ task.title }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.developer }}</td>
      </tr>
   </tbody>
    </table>
    </div>
{% endblock %}

templates/tasksmanager/task_list.html
{% extends 'base.html' %}

<style>
    div#sidebar.col-xs-6.col-sm-3.sidebar-offcanvas#sidebar{
        margin-bottom: -10px;
        margin-top: 10px;
    }
</style>

{% block title %}
    task list
{% endblock %}



{% block article_content %}

    {% include 'navbar.html' %}

    <div class="container" id="div_containing_form">
        <form role="form" method="get" id="task_list_search_form">
            <div class="form-group">
                <span id="is-loading"></span>
                <label></label><span id="search_error" style="color: red"></span>
                <input type="text" class="form-control" name="query" id="search_task" placeholder="请输入非负数数字"/>
                <button type="submit" class="btn btn-primary" id="search_btn">提交查询</button>
            </div>
        </form>
    </div>
    <br><br>
    <br>
    <div class="btn-toolbar" role="toolbar">
        <div class="container" style="font-family: Ubuntu; color: lightslategray; font-size: 20px;">
            <p>对所选择的内容进行操作</p>
        </div>
        <div class="btn-group" style="margin-left: 109px;">
            <button type="button" id="select_all" class="btn btn-success">全选</button>
            <button type="button" id="unselect_all" class="btn btn-primary">反选</button>
            <button class="btn btn-warning" type="button" id="edit">编辑所选</button>
            <button class="btn btn-danger" type="button" id="delete">删除所选</button>
            <script>
                $("button#edit").click(function(){
                    $(this).ajax({
                        url: '{% url 'delete:task_delete' %}',
                        type: 'POST',
                        contentType: 'application/json',
                        dataType: 'json',
                        data: {}
                    })
                })
            </script>
        </div>
    </div>


    <script>
        function search(form) {
            $.ajax({
                url: '{% url "list:task_search_ajax" %}',
                type: 'GET',
                contentType: 'application/json', //向服务器请求的类型
                dataType: 'json',
                data: form.serialize(),
                success: function (response) {
                    if (response.errors !== '没有查到任何内容，请检查您输入的内容是否为task的名称') {
                        $.each(response, function (i, v) {
                        $("#t_body").append("<tr><td>" + v.title + "</td><td>" + v.description +
                        "</td><td>" + v.developer + "</td><td>" +
                        "<input class='checkbox' type='checkbox' id=v.id>"
                        + "</td></tr>");
                    });
                    }else{
                        $("#search_error").html(response.errors);
                    }
                },
                error: function () {
                    alert('ajax request is breakdown')
                }
            });
        }

        $('form#task_list_search_form').on('submit', function (event) {
            event.preventDefault();
            var form = $(this);
            search(form);
        });


        $(document).ready(function () {
            $('#search_task').typeahead({
                ajax: {
                    url: "{% url 'list:task_search_ajax' %}",
                    displayField: 'title',
                    method: 'get'
                }
            });
        })
    </script>

    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12">
            <table class="table table-hover table-striped table-bordered" id="SearchQuery_Table">
                <caption>任务表格</caption>
                <thead id="t_head">
                <tr style="height: 25px;">
                    <th>名称</th>
                    <th>描述</th>
                    <th>所属开发者</th>
                    <th>选择</th>
                </tr>
                </thead>
                <tbody id="t_body">
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" style="margin-top: 15px;">
        <div class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12">
            <div style="font-size: 14px;">共<label style="color: #20A8D8; font-size: 14px;" id="pageCount">0</label>条记录
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12">
            <div id="MainContent_AspNetPager_Msg" class="paginator">
            </div>
            <div class="hidden" id="CurrentPageSize">1</div>
        </div>
    </div>

        {% include 'index_sidebar.html' %}
{% endblock %}

templates/tasksmanager/user_profile.html
{% extends 'base.html' %}

{% block h1 %}
<p>这里是用户中心，只有经过认证的用户可以看见此页面</p>
{% endblock %}