Work_Manager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', 'tasks_manager.views.index', name='public_index'),
                       url(r'^create/', include('tasks_manager.urls', namespace='create')),
                       url(r'^delete', include('tasks_manager.urls', namespace='delete')),
                       url(r'^edit', include('tasks_manager.urls', namespace='edit')),
                       url(r'^search', include('tasks_manager.urls', namespace='search')),
                       url(r'^list-', include('tasks_manager.urls', namespace='list', app_name='tasks_manager')),
                       url(r'^detail', include('tasks_manager.urls', namespace='detail')),
                       url(r'^accounts', include('tasks_manager.urls', namespace='accounts')),
                       url(r'^forum', include('forum.urls', namespace='forums')),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.conf.urls import url, patterns
from .views import login, index, newthread

urlpatterns = patterns('',
                       url(r'login/$', login, name='login'),
                       url(r'', index, name='index'),
                       url(r'/newthread/$', newthread, name='newthread'),
                       )

tasks_manager/urls.py
from django.conf.urls import patterns, url

from .views import UpdateProjectList, task_detail, task_list, task_ajax, project_detail, project_list
from .views import create_task, create_project, create_developer, create_supervisor
from .views import user_login, user_profile, user_logout, task_delete
urlpatterns = patterns('',
                       url(r'_task$', create_task, name='create_task'),
                       url(r'_project$', create_project, name='create_project'),
                       url(r'_developer$', create_developer, name='create_developer'),
                       url(r'_supervisor$', create_supervisor, name='create_supervisor'),
                       url(r'_task$', task_delete, name='task_delete'),
                       url(r'_project/$', UpdateProjectList.as_view(), name='edit_project'),
                       url(r'ajax/$', task_ajax, name='task_search_ajax'),
                       url(r'task_(?P<pk>\d+)$', task_detail, name='task_detail'),
                       url(r'_project_(?P<pk>\d+)$', project_detail, name='project_detail'),
                       url(r'task$', task_list, name='list_task'),
                       url(r'_project$',project_list, name='project_list'),
                       url(r'_login$', user_login, name='user_login'),
                       url(r'_logout$', user_logout, name='user_logout'),
                       url(r'_user_profile', user_profile, name='user_profile'),
                       )

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
{#    <link rel="stylesheet" href="{% static 'css/layout_wide.css'%}">#}
{#    <link rel="stylesheet" href="{% static 'css/font-awsome.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">#}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{#    <script src="{% static 'js/jquery.autocomplete.js' %}"></script>#}
    <script src="{% static 'js/bootstrap-typeahead.min.js' %}"></script>
{#    <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>#}
{#    <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>#}

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
   <div>{% block navbar %}{% endblock %}</div>
    <h1>{% block h1 %}{% endblock %}</h1>
    <article>
        {% block article_content %}{% endblock %}
    </article>
    <footer>
    {% block footer %}{% endblock %}
    </footer>
</body>

</html>

templates/forum_headerfooter.html
<!DOCTYPE html>
<html>
<head>
    <title>Forum</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}">
</head>

<body>
<div id="container">
    <div class="text-center">
        <div id="userinfo">
            {% if user and not user.is_anonymous %}
            Logged in as {{ user.username }}.
{#            <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>#}
            {% else %}
{#            Not logged in.<a href="{% url 'social:begin' 'google-oauth2'%}?next={{ request.path }}">Login with your Google account.</a>#}
            {% endif %}
        </div>
    </div>
{% block content %}
{% endblock %}

<div class="fineprint">These are not the droid you are looking for.</div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}
<head>

</head>
{% block title %}
    index page
{% endblock %}


{% block article_content %}
    {% include 'navbar.html' %}
    {% include 'index_content.html' %}
    {% include 'index_sidebar.html' %}
{% endblock %}

{% block footer %}
    {% include 'index_footer.html' %}
{% endblock %}

templates/index_content.html
<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <br><br>

        <div class="col-xs-12 col-sm-9" id="accordion">
            <p class="pull-right visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
            </p>
            <div class="jumbotron"
                 style="padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px; ">
                <div class="container">
                    <h1>{{ action }}</h1>

                    <div>
                        {% if queryset|length > 0 %}
                            <table>
                                <thead>
                                <tr>
                                    <td>ID</td>
                                    <td>Title</td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for project in queryset %}
                                    <tr>
                                        <td>{{ project.pk }}</td>
                                        <td>{{ project.title }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <span>No project is there.</span>
                        {% endif %}
                    </div>
                    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
                </div>
            </div>


            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion"
                               href="#collapseOne">
                                点击我进行展开，再次点击我进行折叠。第 1 部分
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            Nihil anim keffiyeh helvetica, craft beer labore wes anderson
                            cred nesciunt sapiente ea proident. Ad vegan excepteur butcher
                            vice lomo.
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion"
                               href="#collapseTwo">
                                点击我进行展开，再次点击我进行折叠。第 2 部分
                            </a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            Nihil anim keffiyeh helvetica, craft beer labore wes anderson
                            cred nesciunt sapiente ea proident. Ad vegan excepteur butcher
                            vice lomo.
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion"
                               href="#collapseThree">
                                点击我进行展开，再次点击我进行折叠。第 3 部分
                            </a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            Nihil anim keffiyeh helvetica, craft beer labore wes anderson
                            cred nesciunt sapiente ea proident. Ad vegan excepteur butcher
                            vice lomo.
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion"
                               href="#collapseFour">
                                点击我进行展开，再次点击我进行折叠。第 4 部分
                            </a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                            Nihil anim keffiyeh helvetica, craft beer labore wes anderson
                            cred nesciunt sapiente ea proident. Ad vegan excepteur butcher
                            vice lomo.
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion"
                               href="#collapseFive">
                                点击我进行展开，再次点击我进行折叠。第 5 部分
                            </a>
                        </h4>
                    </div>
                    <div id="collapseFive" class="panel-collapse collapse">
                        <div class="panel-body">
                            Nihil anim keffiyeh helvetica, craft beer labore wes anderson
                            cred nesciunt sapiente ea proident. Ad vegan excepteur butcher
                            vice lomo.
                        </div>
                    </div>
                </div>
            </div>

            <!--/row-->
        </div>
        <!--paginator start-->
        <div class="container" style="">
            <ul class="pager">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;前一页</span>
                    </a>
                </li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;后一页</span>
                    </a>
                </li>
            </ul>
        </div>

        <!--paginator end-->
        <br><br>
    </div>
    <!--/.container-->
</div>

templates/index_footer.html
<style>
    hr {
        border-color: #16bb8e;
    }

    footer {
        background-color: #16bb8e;
        color: #f5f5f5
    }
</style>

<hr>
<div class="container">
    <footer>
        <div class="col col-md-3" style=>
            <div>
                <p>&copy; Your Work-Manager Support 2015</p>
                <address>
                    <strong>Twitter, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>

                <address>
                    <strong>Full Name</strong><br>
                    <a href="mailto:#">first.last@example.com</a>
                </address>
            </div>
        </div>
        <div class="col col-md-3">
            <div>
                <p>
                    未来发展方向以及工作分配
                </p>
            </div>
        </div>
        <div class="col col-md-3">
            <div>
                <p>
                    未来发展方向以及工作分配
                </p>
            </div>
        </div>
        <div class="col col-md-3">
            <div>
                <p>
                    未来发展方向以及工作分配
                </p>
            </div>
        </div>
    </footer>
</div>

templates/index_sidebar.html
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
    <div class="list-group">
        <a href="{% url 'create:create_developer' %}" class="list-group-item">Create
            Developer</a>
        <a href="{% url 'create:create_project' %}" class="list-group-item">Create
            Project</a>
        <a href="{% url 'list:project_list' %}" class="list-group-item">项目列表</a>
        <a href="{% url 'create:create_supervisor' %}"
           class="list-group-item">创建一个管理者</a>
        <a href="{% url 'list:create_task' %}" class="list-group-item">创建一个任务</a>
        <a href="{% url 'list:list_task' %}" class="list-group-item">任务表格</a>
    </div>
</div>

templates/navbar.html
{% block navbar %}
    <style>
        nav.navbar.navbar-fixed-top.navbar-nav{
            background-color:  #16bb8e;
{#            background-color: rgba(14, 155, 110, 0.93);#}
            height: 45px;
        }
        .pager{
            width: 876px;height: 37px;padding-top: 1px; padding-bottom: 1px; margin-left: -26px;
        }
        .pager li a {
            background-color: #006dcc;
        }
        .pager li a:hover {
            background-color: lightseagreen;
        }
        #nav_id  ul li a:hover {
            background-color: #eea236;
            font-size: larger;
        }
        .open>.dropdown-menu{
            display: inline-block;
            background-color: lightseagreen;
        }
        .dropdown, .nav .open>a, .nav .open>a:focus, .nav .open>a:hover{
            background-color: lightseagreen;
        }
        .btn-info{
            border-color: transparent;
        }
        form.navbar-form.navbar-right{
            height: 45px;
        }
        form.navbar-right>button.btn-info{
            background-color: transparent;
            border: dashed #f5f5f5 2px;
        }
        form.navbar-right>button.btn-info:hover{
            background-color: #FFBD5F;
            border-color: transparent;
            color: #080808;
            font-size: larger;
        }
        div.btn-group{
            margin-left: -41px;
        }
        div.btn-group>button.btn.btn-default{
            border-color: transparent;
            background-color: #FFBD5F;
        }
        div#sidebar.col-xs-6.col-sm-3.sidebar-offcanvas{
            float: right;
            margin-top: -45%;
        }
    </style>
    <script>
        $(document).ready(function () {
            $(".navbar-brand, ul a").css('color', '#EEEEEE');
        });
    </script>
    <!-- starting nav-->
    <nav class="navbar navbar-fixed-top navbar-nav" style="" id="nav_id">
        <div class="container" style="height: 45px;">
            <div class="navbar-header" style="height: 45px;">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" style="height: 45px;">Project name</a>
            </div>
            <div id="nav-form">
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search" name="q">
                        <div class="btn-group" style="">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
                {% if authenticated %}
                    <div class="container navbar-right" style="margin-right: -84%" >
                    <a href="{% url 'accounts:user_profile' %}" class="btn btn-info navbar-btn" id="user_profile">用户中心</a>
                    <a href="{% url 'accounts:user_logout' %}" class="btn btn-info navbar-btn" id="logout">退出登录</a>
                    </div>
                {% else %}
                <form class="navbar-right" role="form" action="{% url 'accounts:user_login' %}">
                    <button type="submit" class="btn btn-info navbar-btn" id="login">登录</button>
                    <button type="submit" class="btn btn-info navbar-btn" id="signup">注册</button>
                </form>
                {% endif %}
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav" style="height: 45px;">
                    <li class="active"><a href="{% url 'public_index' %}">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a href="#Task">Tasks Lists</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.nav-collapse -->
            <!-- /drop_down_menu  -->
        </div>
        <!-- /.container -->
    </nav><!-- /.navbar -->
{% endblock %}